### ISSUE TITLE
GPLv3 License issue

### ISSUE THREAD

**Issue by alloy** [manuelbieh/geolib#197] opened 2019-05-30 11:12 UTC
Hi, we’re using this library in one of our projects (thanks for sharing!) and while I was doing some research into licenses I found the following in your code:

https://github.com/manuelbieh/geolib/blob/6ba1b60c22d471e87b026698555212072cd587d9/src/getRhumbLineBearing.ts#L13

It is my understanding that ‘taking’ GPLv3 source is ‘infectious’ and spreads to those that re-use the source. Perhaps the key here is ‘based on’, but IANAL and so I’m wondering if you have more insight into this?

**Comment by manuelbieh** [comment] 2019-05-30 11:14
Can you specify / elaborate on what exactly the issue is?

**Comment by alloy** [comment] 2019-05-30 11:15
> Can you specify / elaborate on what exactly the issue is?

Yeah, sorry about that, I accidentally hit the wrong key combo and submitted too early 🙈

**Comment by manuelbieh** [comment] 2019-05-30 11:17
I think you’re talking about the getRhumbLineBearing function?

**Comment by bt** [comment] 2019-06-06 15:09
IANAL but as I understand, this shouldn’t be a licence violation as the original code is written in PHP and this library merely uses the same algorithm implementation but is rewritten in TypeScript/JavaScript.

**Comment by alloy** [comment] 2019-06-06 16:50
I am pretty sure that porting, rather than a cleanroom implementation, still leaves the GPL license of the original code in place. E.g. https://stackoverflow.com/questions/3256967/what-are-the-copyright-and-licensing-issues-of-porting-code

**Comment by manuelbieh** [comment] 2019-06-06 16:51
@alloy The link you posted seems broken

**Comment by alloy** [comment] 2019-06-06 16:52
Oh, weird, it still works for me. I got there from the first link of this comment https://softwareengineering.stackexchange.com/a/58340

**Comment by manuelbieh** [comment] 2019-06-06 16:56
The formula is pretty surely public domain. That's common knowledge and pure math. The function itself contains one condition and is otherwise completely based on a mathematical formula. I'm not a lawyer either but I am 99% sure I could just remove the link to the source and that would be totally fine and legal.

Put simply, it's not very much different to a function
`function add(a, b) { return a + b; }` which could not be patented or put under a particular license in any form.

**Comment by alloy** [comment] 2019-06-06 17:12
Gotcha, that makes sense to me 👍

**Comment by Zauberfisch** [comment] 2019-12-10 13:46
If this has been resolved, I would suggest closing this issue. Seeing an open issue with the title "license issue" is bound to turn away some people considering using this library

**Comment by manuelbieh** [comment] 2019-12-10 13:56
Good point. I will change the comment to clarify that there's not really a license issue.

**Closed by manuelbieh** 2019-12-10 13:56 UTC
